### ISSUE TITLE
Understanding what it takes to convert .coverage xml to lcov

### ISSUE THREAD

**Issue by ShreyasRmsft** [spekt/vstest.coverage#1]

**Comment by ShreyasRmsft** [comment]
Two available formats to feed into the extension:
lcov.info
lcov.xml

lcov.info looks simpler to implement and doesn't seem very language specific and can allow us to scale later.

Not looking into perf of parsing/writing right now.

**Comment by ShreyasRmsft** [comment]
Documentation for .gcov coverage file format http://man7.org/linux/man-pages/man1/gcov.1.html

**Comment by harshjain2** [comment]
A .coverage file can be converted to XML file using the below command:
`CodeCoverage.exe analyze /output:results.xml file.coverage`

Once we have the XML file, we need a mapper to convert it to lcov.xml format.

**Comment by harshjain2** [comment]
@ShreyasRmsft Do we have the documentation for the XML format generated using CodeCoverage.exe?
