### ISSUE TITLE
Converting xml to Internal Data Model

### ISSUE THREAD

**Issue by vagisha-nidhi** [spekt/vstest.coverage#16]
# Creating internal data model from xml file 
Present internal data model specifics.

## Internal data model consists of the following information
1. start_line
2. end_line
3. source_id
4. covered

Covered can be either of the following : yes/no/partial
Source Ids in the xml file are module specific. We generate unique ids for sources for internal data model.

**Comment by smadala** [comment]
Fixed via https://github.com/spekt/vstest.coverage/pull/24
